spring.application.name=semiproject

spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.hikari.username=root
spring.datasource.hikari.password=1111
spring.datasource.hikari.auto-commit=true

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/sql-*.xml
logging.level.org.cloud.mapper=debug

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

api.recipe.key=2b88b557feb7de8e59fd2c0ec3fa6c162e816bdb588c91578d1c228140b3c019
mybatis.mapper-locations=classpath:mapper/sql-*.xml
logging.level.org.cloud.mapper=debug
spring.datasource.hikari.auto-commit=true
google.gemini.api.key=${GEMINI_API_KEY}
google.gemini.model.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent
spring.thymeleaf.check-template-location=false

# 파일 서빙 base URL
# 로컬 개발
file.base-url=http://localhost:8080
# AWS 배포 시 아래 주석 해제하고 위 로컬 설정 주석 처리
# file.base-url=https://버킷명.s3.ap-northeast-2.amazonaws.com
